# Generated by Django 3.1.1 on 2020-10-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartsOfAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_number', models.IntegerField()),
                ('report_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.chartsofaccount')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralBuisnessPostingSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_of_goods_sold_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cosgs_account', to='app.chartsofaccount')),
            ],
        ),
        migrations.CreateModel(
            name='GerenalBusinessPostingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPostingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvItemLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sub_total', models.FloatField()),
                ('total', models.FloatField()),
                ('total_tax', models.FloatField()),
                ('state', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_form', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VatPostingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vat', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPostingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payable_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chartsofaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('credit_limit', models.FloatField()),
                ('debit_limit', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general_buisness_posting_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.gerenalbusinesspostinggroup')),
                ('vat_posting_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vatpostinggroup')),
                ('vendor_posting_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.vendorpostinggroup')),
            ],
        ),
        migrations.CreateModel(
            name='VatPostingSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_vat', to='app.vatpostinggroup')),
                ('vat_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chartsofaccount')),
                ('vendor_vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_vat', to='app.vatpostinggroup')),
            ],
        ),
        migrations.AddField(
            model_name='vatpostinggroup',
            name='grouping',
            field=models.ManyToManyField(related_name='_vatpostinggroup_grouping_+', through='app.VatPostingSetup', to='app.VatPostingGroup'),
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.journal')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.chartsofaccount')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry', to='app.journal')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.journal')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('InventoryPostingGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventorypostinggroup')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invitemcategory')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unitofmeasurement')),
                ('vat_posting_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vatpostinggroup')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_invoiceline', to='app.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_master_data', to='app.itemmasterdata')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.journal'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
        migrations.CreateModel(
            name='InvItemMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_item_master', to='app.itemmasterdata')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPostingSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_account', to='app.chartsofaccount')),
                ('inventory_account_intrim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_account_intrim', to='app.chartsofaccount')),
                ('item_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_location_group', to='app.invitemlocation')),
                ('item_posting_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_posting_group', to='app.inventorypostinggroup')),
            ],
        ),
        migrations.AddField(
            model_name='inventorypostinggroup',
            name='grouping',
            field=models.ManyToManyField(through='app.InventoryPostingSetup', to='app.InvItemLocation'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='app.invitemcategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_master', to='app.itemmasterdata')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invitemlocation')),
            ],
        ),
        migrations.AddField(
            model_name='gerenalbusinesspostinggroup',
            name='grouping',
            field=models.ManyToManyField(through='app.GeneralBuisnessPostingSetup', to='app.InvItemCategory'),
        ),
        migrations.AddField(
            model_name='generalbuisnesspostingsetup',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category_posting', to='app.invitemcategory'),
        ),
        migrations.AddField(
            model_name='generalbuisnesspostingsetup',
            name='purchase_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_account', to='app.chartsofaccount'),
        ),
        migrations.AddField(
            model_name='generalbuisnesspostingsetup',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_business_posting', to='app.gerenalbusinesspostinggroup'),
        ),
    ]
