# Generated by Django 3.1.1 on 2020-09-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPostingGroup',
            new_name='InvItemLocation',
        ),
        migrations.RemoveField(
            model_name='itemmasterdata',
            name='item_group',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.invitemlocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitemcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2012-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitemcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemmasterdata',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.invitemcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmasterdata',
            name='total_quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemmasterdata'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendorpostinggroup',
            name='grouping',
            field=models.ManyToManyField(through='app.VendorPostingSetup', to='app.InvItemCategory'),
        ),
        migrations.AlterField(
            model_name='vendorpostingsetup',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invitemcategory'),
        ),
    ]
