# Generated by Django 3.1.1 on 2020-09-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200930_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasurement',
            old_name='symbol',
            new_name='short_form',
        ),
        migrations.AlterField(
            model_name='itemmasterdata',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
