# Generated by Django 3.1.1 on 2020-09-30 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200930_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendorpostinggroup'),
        ),
    ]
