# Generated by Django 3.1.1 on 2020-09-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200930_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartsofaccount',
            name='account_number',
            field=models.IntegerField(default=11111),
            preserve_default=False,
        ),
    ]
