# Generated by Django 3.1.1 on 2020-09-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chartsofaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.journal'),
            preserve_default=False,
        ),
    ]
