# Generated by Django 3.1.1 on 2020-09-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_invoice_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemmasterdata'),
        ),
    ]
