# Generated by Django 3.1.1 on 2020-09-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200930_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmasterdata',
            name='vat_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vatpostinggroup'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vat_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vatpostinggroup'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_invoiceline', to='app.invoice'),
        ),
    ]
