# Generated by Django 3.1.1 on 2020-10-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200930_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmasterdata',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_master_data', to='app.itemmasterdata'),
        ),
    ]
