# Generated by Django 3.1.1 on 2020-10-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201001_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tax',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tax',
            field=models.FloatField(blank=True),
        ),
    ]
