# Generated by Django 3.1.1 on 2020-10-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201001_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.CharField(default='some description', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tax',
            field=models.FloatField(),
        ),
    ]
