from django.urls import path
from app import views

urlpatterns = [
    path("journals", views.Journals_LA.as_view()),
    path("journals/<int:id>", views.Journals_RUD.as_view()),
    path("charts-of-accounts", views.ChartsOfAccount_LA.as_view()),
    path("charts-of-accounts/<int:id>", views.ChartsOfAccount_RUD.as_view()),
    path("unit-of-measurements", views.UnitOfMeasurement_LA.as_view()),
    path("unit-of-measurements/<int:id>", views.UnitOfMeasurement_RUD.as_view()),
    path("item-locations", views.InvItemLocation_LA.as_view()),
    path("item-locations/<int:id>", views.InvItemLocation_RUD.as_view()),
    path("item-categories", views.ItemCategory_LA.as_view()),
    path("item-categories/<int:id>", views.ItemCategory_RUD.as_view()),
    path("item-movements", views.ItemMovements_LA.as_view()),
    path("item-movements/<int:id>", views.ItemMovements_RUD.as_view()),
    path("items", views.Items_LA.as_view()),
    path("items/<int:id>", views.Items_RUD.as_view()),
    path("items-masterdata", views.ItemsMasterData_LA.as_view()),
    path("items-masterdata/<int:id>", views.ItemsMasterData_RUD.as_view()),
    path("vendors", views.Vendor_LA.as_view()),
    path("vendors/<int:id>", views.Vendor_RUD.as_view()),
    path("vendor-posting-groups", views.VendorPostingGroup_LA.as_view()),
    path("vendor-posting-groups/<int:id>", views.VendorPostingGroup_RUD.as_view()),
    path("vat-posting-groups", views.VatPostingGroup_LA.as_view()),
    path("vat-posting-groups/<int:id>", views.VatPostingGroup_RUD.as_view()),
    path("vat-posting-setups", views.VatPostingSetup_LA.as_view()),
    path("var-posting-setups/<int:id>", views.VatPostingSetup_RUD.as_view()),
    path("vendor-posting-setups", views.VendorPostingSetup_LA.as_view()),
    path("vendor-posting-setups/<int:id>", views.VendorPostingSetup_RUD.as_view()),
    path("invoices", views.Invoice_LA.as_view()),
    path("invoices/<int:id>", views.Invoice_RUD.as_view()),
    ]
